# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\tinference\"\x1f\n\x0ePredictRequest\x12\r\n\x05input\x18\x01 \x01(\t\"\x1e\n\x0cPredictReply\x12\x0e\n\x06output\x18\x01 \x01(\t2J\n\tInference\x12=\n\x07Predict\x12\x19.inference.PredictRequest\x1a\x17.inference.PredictReplyB9Z7github.com/Bipul-Dubey/ai-knowledgebase/proto;inferenceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z7github.com/Bipul-Dubey/ai-knowledgebase/proto;inference'
  _globals['_PREDICTREQUEST']._serialized_start=31
  _globals['_PREDICTREQUEST']._serialized_end=62
  _globals['_PREDICTREPLY']._serialized_start=64
  _globals['_PREDICTREPLY']._serialized_end=94
  _globals['_INFERENCE']._serialized_start=96
  _globals['_INFERENCE']._serialized_end=170
# @@protoc_insertion_point(module_scope)
